# Generated by Django 4.1.5 on 2023-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройку', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.RemoveField(
            model_name='telesettings',
            name='tg_messsage',
        ),
        migrations.AddField(
            model_name='telesettings',
            name='tg_message',
            field=models.TextField(default=222, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
    ]
